### ISSUE TITLE
Pill blip not showing up 50% of time

### ISSUE THREAD

**Issue by Spydermonk** [qbcore-framework/qb-oxyrun#7]
For qb-oxyrun
Can dm on discord  if need Spyder88#7516
will go to the start location pay the 6,500 to do the job car will spawn will get notification saying gps will be updated shortly.
ill jump in car wait 5-10 minutes periodically checking map for Pill marker wont have one. will move spawned car restart job paying another 6,500 hop in car i will get the waypoint. can also provide a fivem qbcore server to test on for bug testing.

**Comment by GhzGarage** [comment]
Should be fixed
